import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/*  data-theme="light" in html would change the theme in next js */}
      <body className={inter.className}>
        <Navbar />
        <main className="pl-3">{children}</main>
      </body>
    </html>
  );
}
